<h1>numpy</h1>

<h2>Creating a numpy array</h2>

In [2]:
import numpy as np
ax = np.array([1,2,3,4,5])
print(ax,id(ax),len(ax))

[1 2 3 4 5] 2412458167392 5


<h2>Specifying the type</h2>
<h3>Useful when reading a text stream directly into a numerical array</h3>

In [3]:
x=['1','2','3']
xi = np.array(x,'int')
xf = np.array(x,'float')
xs = np.array(x,'str')
print(xi,xf,xs,sep='\n')

[1 2 3]
[1. 2. 3.]
['1' '2' '3']


<h2>Basic operations</h2>

In [5]:
x = np.array([13,24,21.2,17.6,21.7],'float')
print(x.sum(),x.mean(),x.std(),sep='\n')

97.50000000000001
19.500000000000004
3.8429155598321434


<h2>Multi-dimensional arrays</h2>

In [4]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
print(ax)

[[ 0.  1.  2.  3.  4.  5.]
 [10. 11. 12. 13. 14. 15.]
 [20. 21. 22. 23. 24. 25.]]


<h3>Indexing</h3>

In [6]:
ax[1,3] #indexing

13.0

<h3>Slicing</h3>

In [8]:
ax[1:3,2:4]  # נרצה לשלוף שורות 1-2 ואת עמודות 2-3


array([[12., 13.],
       [22., 23.]])

In [9]:
ax[:,2:]

array([[ 2.,  3.,  4.,  5.],
       [12., 13., 14., 15.],
       [22., 23., 24., 25.]])

<h3>Reshaping</h3>


In [10]:
print(ax.shape)
ax.reshape(9,2)


(3, 6)


array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [10., 11.],
       [12., 13.],
       [14., 15.],
       [20., 21.],
       [22., 23.],
       [24., 25.]])

In [11]:
ax.reshape(10,3)

ValueError: cannot reshape array of size 18 into shape (10,3)

<h3>Creating initialized arrays</h3>

In [12]:
ax = np.arange(10)
print(ax)
ay = np.array([np.arange(10),np.arange(10)])
print(ay)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


In [13]:
ax = np.ones(10)
print(ax)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
ax = np.arange(10)**2
print(ax)

[ 0  1  4  9 16 25 36 49 64 81]


In [15]:
np.identity(10)  #מטריצת היחידה 

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

<h3>Matrix multiplication</h3>


In [16]:
ax = np.arange(10)
ay = np.array([ax,ax])
#Scalar multiplication
ay*2

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [ ]:
np.dot(ay,ay.reshape(10,2)) #Dot product

<h3>Comparing numpy arrays with lists</h3>

In [18]:
n=10
ax = np.array([np.arange(n)**2,np.arange(n)**3])
ay = ax.transpose()
print(ax)
print(ay)
np.dot(ax,ay)

[[  0   1   4   9  16  25  36  49  64  81]
 [  0   1   8  27  64 125 216 343 512 729]]
[[  0   0]
 [  1   1]
 [  4   8]
 [  9  27]
 [ 16  64]
 [ 25 125]
 [ 36 216]
 [ 49 343]
 [ 64 512]
 [ 81 729]]


array([[ 15333, 120825],
       [120825, 978405]], dtype=int32)

### Comparing running time - np.arrays vs. lists

<h4>Functionalize this</h4>


In [27]:
def dotproduct(n):
    ax = np.array([np.arange(n)**2,np.arange(n)**3])
    ay = ax.transpose()
    import datetime
    start = datetime.datetime.now()
    np.dot(ax,ay)
    end = datetime.datetime.now()
    return end-start
    
dotproduct(100000)    

datetime.timedelta(0)

<h4>Do the same with python lists</h4>


In [29]:

def dot_product_lists(n):
    x = [x**2 for x in range(n)]
    y = [x**3 for x in range(n)]
    ax = [x,y]
    ay = [list(i) for i in zip(*ax)]
    import datetime
    start = datetime.datetime.now()
    [[sum(a*b for a,b in zip(X_row,Y_col)) for Y_col in zip(*ay)] for X_row in ax]
    end = datetime.datetime.now()
    return end-start
    
dot_product_lists(100000)

datetime.timedelta(microseconds=139856)

In [30]:
for n in [10,100,1000,10000]:
    numpy_result = dotproduct(n)
    list_result = dot_product_lists(n)
    print(n,numpy_result,list_result,sep='\t')

10	0:00:00	0:00:00
100	0:00:00	0:00:00
1000	0:00:00	0:00:00.000995
10000	0:00:00	0:00:00.013963


<h3>Selecting elements from an np array</h3>

In [31]:
x=[[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25]]
ax=np.array(x,float)
np.where(ax%2==0,1,0)

array([[1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1, 0]])

In [ ]:

#linalg, a linear algebra module
#functions dealing with polynomials, differentials, etc


<h3>Random number support in numpy</h3>

In [33]:
np.random.normal(size=10)  # creates and array of 10 numbers, normally distributed with mean = 0 and sd = 1
#np.random.normal(size=(100,100)) 
#np.random.exponential() 
#np.random.exponential(1.0,size=(6,3)) 
#np.random.randint(-10,10,size=(9,9)) # uniform distribution

array([ 1.51050758,  0.30334531,  0.13339365,  0.41785825, -0.31426442,
       -0.96498162,  0.44057553,  0.05453631, -0.39749671, -0.18013647])